openapi: 3.2.0
info:
  version: '1'
  title: Adyen Terminal Cardreaderapdu API
  description: The Adyen Terminal API lets you make payments, issue refunds, collect shopper information, and perform other shopper-terminal interactions using a payment terminal supplied by Adyen.
servers:
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/sync
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/async
- description: with local-hosting
  url: <local-terminal-IP-address>
tags:
- name: Cardreaderapdu
paths:
  /cardreaderapdu:
    post:
      description: It contains the APDU request to send to the chip of the card, and a possible invitation message to display on the CashierInterface or the CustomerInterface. Content of the Card Reader APDU Request message.
      summary: Adyen CardReaderAPDU Request
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardReaderAPDURequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardReaderAPDUResponse'
              examples:
                operation200Example:
                  summary: Default operation 200 response
                  x-microcks-default: true
                  value:
                    Response: example_value
                    APDUData: example_value
                    CardStatusWords: active
          description: It contains the result of the requested service, APDU response sent by the chip of the card in response to the APDU request. Content of the Card Reader APDU Response message.
      tags:
      - Cardreaderapdu
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: postCardreaderapdu
      x-operation-id-source: derived
components:
  schemas:
    CardReaderAPDUResponse:
      type: object
      description: It contains the result of the requested service, APDU response sent by the chip of the card in response to the APDU request. Content of the Card Reader APDU Response message.
      properties:
        Response:
          $ref: '#/components/schemas/Response'
        APDUData:
          type: string
          format: byte
          pattern: ^.+$
          description: Data field of the APDU command (Lc + Data).
        CardStatusWords:
          type: string
          format: byte
          pattern: ^.{2,2}$
          description: Status of a smartcard response to a command (SW1-SW2).
      required:
      - Response
      - CardStatusWords
    CardReaderAPDURequest:
      type: object
      description: It contains the APDU request to send to the chip of the card, and a possible invitation message to display on the CashierInterface or the CustomerInterface. Content of the Card Reader APDU Request message.
      properties:
        APDUClass:
          type: string
          format: byte
          pattern: ^.{1,1}$
          description: Class field of the APDU command (CLA).
        APDUInstruction:
          type: string
          format: byte
          pattern: ^.{1,1}$
          description: Instruction field of the APDU command (INS).
        APDUPar1:
          type: string
          format: byte
          pattern: ^.{1,1}$
          description: Parameter 1 field of the APDU command (P1).
        APDUPar2:
          type: string
          format: byte
          pattern: ^.{1,1}$
          description: Parameter 2 field of the APDU command(P2).
        APDUData:
          type: string
          format: byte
          pattern: ^.+$
          description: Data field of the APDU command (Lc + Data).
        APDUExpectedLength:
          type: string
          format: byte
          pattern: ^.{1,1}$
          description: Expected length of the data field of the APDU response to the command (Le).
      required:
      - APDUClass
      - APDUInstruction
      - APDUPar1
      - APDUPar2
    ErrorCondition:
      type: string
      enum:
      - Aborted
      - Busy
      - Cancel
      - DeviceOut
      - InProgress
      - InsertedCard
      - InvalidCard
      - LoggedOut
      - MessageFormat
      - NotAllowed
      - NotFound
      - PaymentRestriction
      - Refusal
      - UnavailableDevice
      - UnavailableService
      - UnreachableHost
      - WrongPIN
    Result:
      type: string
      enum:
      - Failure
      - Partial
      - Success
    Response:
      type: object
      description: If Result is Success, ErrorCondition is absent or not used in the processing of the message. In the other cases, the ErrorCondition has to be present and can refine the processing of the message response. AdditionalResponse gives more information about the success or the failure of the message request processing, for logging without real time involvements. Result of a message request processing.
      properties:
        Result:
          $ref: '#/components/schemas/Result'
        ErrorCondition:
          $ref: '#/components/schemas/ErrorCondition'
        AdditionalResponse:
          type: string
          pattern: ^.+$
          description: If present, the POI logs it for further examination.
      required:
      - Result
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
