openapi: 3.2.0
info:
  version: '1'
  title: Adyen Terminal Reconciliation API
  description: The Adyen Terminal API lets you make payments, issue refunds, collect shopper information, and perform other shopper-terminal interactions using a payment terminal supplied by Adyen.
servers:
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/sync
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/async
- description: with local-hosting
  url: <local-terminal-IP-address>
tags:
- name: Reconciliation
paths:
  /reconciliation:
    post:
      description: It conveys Information related to the Reconciliation requested by the Sale System. Content of the Reconciliation Request message.
      summary: Adyen Reconciliation Request
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReconciliationRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReconciliationResponse'
              examples:
                operation200Example:
                  summary: Default operation 200 response
                  x-microcks-default: true
                  value:
                    Response: example_value
                    ReconciliationType: standard
                    POIReconciliationID: 500
                    TransactionTotals:
                    - example_value
          description: It conveys Information related to the Reconciliation transaction processed by the POI System. Content of the Reconciliation Response message.
      tags:
      - Reconciliation
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: postReconciliation
      x-operation-id-source: derived
components:
  schemas:
    ReconciliationResponse:
      type: object
      description: It conveys Information related to the Reconciliation transaction processed by the POI System. Content of the Reconciliation Response message.
      properties:
        Response:
          $ref: '#/components/schemas/Response'
        ReconciliationType:
          $ref: '#/components/schemas/ReconciliationType'
        POIReconciliationID:
          type: integer
          description: Absent if ReconciliationType is AcquirerReconciliation.
        TransactionTotals:
          type: array
          items:
            $ref: '#/components/schemas/TransactionTotals'
      required:
      - Response
      - ReconciliationType
    LoyaltyTotals:
      type: object
      description: Totals of the loyalty transaction during the reconciliation period.
      properties:
        TransactionType:
          $ref: '#/components/schemas/TransactionType'
        TransactionCount:
          type: integer
          description: Number of processed transaction during the period.
        TransactionAmount:
          type: number
          maximum: 99999999.999999
          minimum: 0
          description: Sum of amount of processed transaction during the period.
      required:
      - TransactionType
      - TransactionCount
      - TransactionAmount
    TransactionTotals:
      type: object
      description: If Result is Success, contains all the totals, classified as required by the Sale in the message request. At least, transaction totals are provided per Acquirer, Acquirer Settlement, and Card Brand. Result of the Sale to POI Reconciliation processing.
      properties:
        PaymentInstrumentType:
          $ref: '#/components/schemas/PaymentInstrumentType'
        AcquirerID:
          type: integer
          description: If available.
        HostReconciliationID:
          type: string
          pattern: ^.+$
          description: If available.
        CardBrand:
          type: string
          pattern: ^.+$
          description: If configured to present totals per card brand, and Response.Result is Success.
        POIID:
          type: string
          pattern: ^.+$
          description: If requested in the message request.
        SaleID:
          type: string
          pattern: ^.+$
          description: If requested in the message request.
        OperatorID:
          type: string
          pattern: ^.+$
          description: If requested in the message request.
        ShiftNumber:
          type: string
          pattern: ^.+$
          description: If requested in the message request.
        TotalsGroupID:
          type: string
          pattern: ^.{1,16}$
          description: If requested in the message request.
        PaymentCurrency:
          type: string
          pattern: ^[A-Z]{3,3}$
          description: Currency of a monetary amount.
        PaymentTotals:
          type: array
          items:
            $ref: '#/components/schemas/PaymentTotals'
        LoyaltyUnit:
          $ref: '#/components/schemas/LoyaltyUnit'
        LoyaltyCurrency:
          type: string
          pattern: ^[A-Z]{3,3}$
          description: If LoyaltyUnit is Monetary.
        LoyaltyTotals:
          type: array
          items:
            $ref: '#/components/schemas/LoyaltyTotals'
      required:
      - PaymentInstrumentType
    ReconciliationRequest:
      type: object
      description: It conveys Information related to the Reconciliation requested by the Sale System. Content of the Reconciliation Request message.
      properties:
        ReconciliationType:
          $ref: '#/components/schemas/ReconciliationType'
        AcquirerID:
          type: array
          items:
            type: integer
            description: Could be present only if ReconciliationType is AcquirerReconciliation or AcquirerSynchronisation.
        POIReconciliationID:
          type: integer
          description: Absent if ReconciliationType is not PreviousReconciliation.
      required:
      - ReconciliationType
    TransactionType:
      type: string
      enum:
      - Award
      - CashAdvance
      - CompletedDeffered
      - CompletedReservation
      - Credit
      - Debit
      - Declined
      - Failed
      - FirstReservation
      - IssuerInstalment
      - OneTimeReservation
      - Rebate
      - Redemption
      - ReverseAward
      - ReverseCredit
      - ReverseDebit
      - ReverseRebate
      - ReverseRedemption
      - UpdateReservation
    PaymentInstrumentType:
      type: string
      enum:
      - Card
      - Cash
      - Check
      - Mobile
      - StoredValue
    PaymentTotals:
      type: object
      description: Totals of the payment transaction during the reconciliation period.
      properties:
        TransactionType:
          $ref: '#/components/schemas/TransactionType'
        TransactionCount:
          type: integer
          description: Number of processed transaction during the period.
        TransactionAmount:
          type: number
          maximum: 99999999.999999
          minimum: 0
          description: Sum of amount of processed transaction during the period.
      required:
      - TransactionType
      - TransactionCount
      - TransactionAmount
    LoyaltyUnit:
      type: string
      enum:
      - Monetary
      - Point
    ReconciliationType:
      type: string
      enum:
      - AcquirerReconciliation
      - AcquirerSynchronisation
      - PreviousReconciliation
      - SaleReconciliation
    ErrorCondition:
      type: string
      enum:
      - Aborted
      - Busy
      - Cancel
      - DeviceOut
      - InProgress
      - InsertedCard
      - InvalidCard
      - LoggedOut
      - MessageFormat
      - NotAllowed
      - NotFound
      - PaymentRestriction
      - Refusal
      - UnavailableDevice
      - UnavailableService
      - UnreachableHost
      - WrongPIN
    Result:
      type: string
      enum:
      - Failure
      - Partial
      - Success
    Response:
      type: object
      description: If Result is Success, ErrorCondition is absent or not used in the processing of the message. In the other cases, the ErrorCondition has to be present and can refine the processing of the message response. AdditionalResponse gives more information about the success or the failure of the message request processing, for logging without real time involvements. Result of a message request processing.
      properties:
        Result:
          $ref: '#/components/schemas/Result'
        ErrorCondition:
          $ref: '#/components/schemas/ErrorCondition'
        AdditionalResponse:
          type: string
          pattern: ^.+$
          description: If present, the POI logs it for further examination.
      required:
      - Result
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
