openapi: 3.2.0
info:
  version: '1'
  title: Adyen Terminal Logout API
  description: The Adyen Terminal API lets you make payments, issue refunds, collect shopper information, and perform other shopper-terminal interactions using a payment terminal supplied by Adyen.
servers:
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/sync
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/async
- description: with local-hosting
  url: <local-terminal-IP-address>
tags:
- name: Logout
paths:
  /logout:
    post:
      description: Empty. Content of the Logout Request message.
      summary: Adyen Logout Request
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
              examples:
                operation200Example:
                  summary: Default operation 200 response
                  x-microcks-default: true
                  value:
                    Response: example_value
          description: It conveys the result of the Logout. Content of the Logout Response message.
      tags:
      - Logout
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: postLogout
      x-operation-id-source: derived
components:
  schemas:
    LogoutResponse:
      type: object
      description: It conveys the result of the Logout. Content of the Logout Response message.
      properties:
        Response:
          $ref: '#/components/schemas/Response'
      required:
      - Response
    LogoutRequest:
      type: object
      description: Empty. Content of the Logout Request message.
      properties:
        MaintenanceAllowed:
          type: boolean
          default: false
    ErrorCondition:
      type: string
      enum:
      - Aborted
      - Busy
      - Cancel
      - DeviceOut
      - InProgress
      - InsertedCard
      - InvalidCard
      - LoggedOut
      - MessageFormat
      - NotAllowed
      - NotFound
      - PaymentRestriction
      - Refusal
      - UnavailableDevice
      - UnavailableService
      - UnreachableHost
      - WrongPIN
    Result:
      type: string
      enum:
      - Failure
      - Partial
      - Success
    Response:
      type: object
      description: If Result is Success, ErrorCondition is absent or not used in the processing of the message. In the other cases, the ErrorCondition has to be present and can refine the processing of the message response. AdditionalResponse gives more information about the success or the failure of the message request processing, for logging without real time involvements. Result of a message request processing.
      properties:
        Result:
          $ref: '#/components/schemas/Result'
        ErrorCondition:
          $ref: '#/components/schemas/ErrorCondition'
        AdditionalResponse:
          type: string
          pattern: ^.+$
          description: If present, the POI logs it for further examination.
      required:
      - Result
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
