openapi: 3.2.0
info:
  version: '71'
  x-publicVersion: true
  title: Adyen Checkout Method API
  description: This is the description of your API.
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
servers:
- url: https://checkout-test.adyen.com/v71
tags:
- name: Method
paths:
  /storedPaymentMethods/{storedPaymentMethodId}:
    delete:
      tags:
      - Method
      summary: Adyen Delete a Token for Stored Payment Details
      description: Deletes the token identified in the path. The token can no longer be used with payment requests.
      x-addedInVersion: '70'
      operationId: delete-storedPaymentMethods-storedPaymentMethodId
      x-sortIndex: 4
      x-methodName: deleteTokenForStoredPaymentDetails
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      parameters:
      - description: The unique identifier of the token.
        name: storedPaymentMethodId
        in: path
        required: true
        schema:
          type: string
      - description: 'Your reference to uniquely identify this shopper, for example user ID or account ID. Minimum length: 3 characters.

          > Your reference must not include personally identifiable information (PII), for example name or email address.'
        name: shopperReference
        in: query
        required: true
        schema:
          type: string
      - description: Your merchant account.
        name: merchantAccount
        in: query
        required: true
        schema:
          type: string
      responses:
        '204':
          description: 'No Content - look at the actual response code for the status of the request. '
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
