openapi: 3.2.0
info:
  version: '1'
  title: Adyen Terminal Print API
  description: The Adyen Terminal API lets you make payments, issue refunds, collect shopper information, and perform other shopper-terminal interactions using a payment terminal supplied by Adyen.
servers:
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/sync
- description: with cloud integration
  url: https://terminal-api-test.adyen.com/async
- description: with local-hosting
  url: <local-terminal-IP-address>
tags:
- name: Print
paths:
  /print:
    post:
      description: It conveys the data to print and the way to process the print. It contains the complete content to print. Content of the Print Request message.
      summary: Adyen Print Request
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrintRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrintResponse'
              examples:
                operation200Example:
                  summary: Default operation 200 response
                  x-microcks-default: true
                  value:
                    DocumentQualifier: example_value
                    Response: example_value
          description: It conveys the result of the print, parallel to the message request, except if response not required and absent. Content of the Print Response message.
      tags:
      - Print
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: postPrint
      x-operation-id-source: derived
components:
  schemas:
    PredefinedContent:
      type: object
      description: It conveys Information related to the predefined message. Reference of a predefined message to display or print.
      properties:
        ReferenceID:
          type: string
          pattern: ^.+$
          description: Identification of a predefined message to display or print.
        Language:
          type: string
          pattern: ^[a-z]{2,2}$
          description: Identification of a language.
      required:
      - ReferenceID
    Result:
      type: string
      enum:
      - Failure
      - Partial
      - Success
    OutputBarcode:
      type: object
      properties:
        BarcodeType:
          $ref: '#/components/schemas/BarcodeType'
        BarcodeValue:
          type: string
          pattern: ^.+$
      required:
      - BarcodeValue
    PrintResponse:
      type: object
      description: It conveys the result of the print, parallel to the message request, except if response not required and absent. Content of the Print Response message.
      properties:
        DocumentQualifier:
          $ref: '#/components/schemas/DocumentQualifier'
        Response:
          $ref: '#/components/schemas/Response'
      required:
      - DocumentQualifier
      - Response
    PrintRequest:
      type: object
      description: It conveys the data to print and the way to process the print. It contains the complete content to print. Content of the Print Request message.
      properties:
        PrintOutput:
          $ref: '#/components/schemas/PrintOutput'
      required:
      - PrintOutput
    Color:
      type: string
      enum:
      - Black
      - Blue
      - Cyan
      - Green
      - Magenta
      - Red
      - White
      - Yellow
    ErrorCondition:
      type: string
      enum:
      - Aborted
      - Busy
      - Cancel
      - DeviceOut
      - InProgress
      - InsertedCard
      - InvalidCard
      - LoggedOut
      - MessageFormat
      - NotAllowed
      - NotFound
      - PaymentRestriction
      - Refusal
      - UnavailableDevice
      - UnavailableService
      - UnreachableHost
      - WrongPIN
    OutputFormat:
      type: string
      enum:
      - BarCode
      - MessageRef
      - Text
      - XHTML
    Response:
      type: object
      description: If Result is Success, ErrorCondition is absent or not used in the processing of the message. In the other cases, the ErrorCondition has to be present and can refine the processing of the message response. AdditionalResponse gives more information about the success or the failure of the message request processing, for logging without real time involvements. Result of a message request processing.
      properties:
        Result:
          $ref: '#/components/schemas/Result'
        ErrorCondition:
          $ref: '#/components/schemas/ErrorCondition'
        AdditionalResponse:
          type: string
          pattern: ^.+$
          description: If present, the POI logs it for further examination.
      required:
      - Result
    Alignment:
      type: string
      enum:
      - Centred
      - Justified
      - Left
      - Right
    ResponseMode:
      type: string
      enum:
      - Immediate
      - NotRequired
      - PrintEnd
      - SoundEnd
    CharacterStyle:
      type: string
      enum:
      - Bold
      - Italic
      - Normal
      - Underline
    OutputText:
      type: object
      description: It conveys Information related to the content of the text message and its format. All the data elements related to the format of the text to display or print are parameters valid for the whole Text content. Content of text message to display or print.
      properties:
        Text:
          type: string
        CharacterSet:
          type: integer
        Font:
          type: string
          pattern: ^.+$
        StartRow:
          type: integer
          minimum: 1
          maximum: 500
        StartColumn:
          type: integer
          minimum: 1
          maximum: 500
        Color:
          $ref: '#/components/schemas/Color'
        CharacterWidth:
          $ref: '#/components/schemas/CharacterWidth'
        CharacterHeight:
          $ref: '#/components/schemas/CharacterHeight'
        CharacterStyle:
          $ref: '#/components/schemas/CharacterStyle'
        Alignment:
          $ref: '#/components/schemas/Alignment'
        EndOfLineFlag:
          type: boolean
          default: true
      required:
      - Text
    CharacterHeight:
      type: string
      enum:
      - DoubleHeight
      - HalfHeight
      - SingleHeight
    PrintOutput:
      type: object
      properties:
        DocumentQualifier:
          $ref: '#/components/schemas/DocumentQualifier'
        ResponseMode:
          $ref: '#/components/schemas/ResponseMode'
        IntegratedPrintFlag:
          type: boolean
          default: false
        RequiredSignatureFlag:
          type: boolean
          default: false
        OutputContent:
          $ref: '#/components/schemas/OutputContent'
      required:
      - DocumentQualifier
      - ResponseMode
      - OutputContent
    BarcodeType:
      type: string
      enum:
      - Code128
      - Code25
      - EAN13
      - EAN8
      - PDF417
      - QRCode
      - UPCA
    OutputContent:
      type: object
      description: This is a sequence of elements if they have different formats. Content to display or print.
      properties:
        OutputFormat:
          $ref: '#/components/schemas/OutputFormat'
        PredefinedContent:
          $ref: '#/components/schemas/PredefinedContent'
        OutputText:
          type: array
          items:
            $ref: '#/components/schemas/OutputText'
        OutputXHTML:
          type: string
          format: byte
          pattern: ^.{0,262144}$
          description: Mandatory, if OutputFormat is XHTML, not allowed otherwise.
        OutputBarcode:
          $ref: '#/components/schemas/OutputBarcode'
      required:
      - OutputFormat
    DocumentQualifier:
      type: string
      enum:
      - CashierReceipt
      - CustomerReceipt
      - Document
      - Journal
      - SaleReceipt
      - Voucher
    CharacterWidth:
      type: string
      enum:
      - DoubleWidth
      - SingleWidth
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
