openapi: 3.1.0
info:
  version: '6'
  x-publicVersion: true
  title: Adyen Account acceptDispute Cardorders API
  description: "This API is used for the classic integration. If you are just starting your implementation, refer to our [new integration guide](https://docs.adyen.com/marketplaces-and-platforms) instead.\n\nThe Account API provides endpoints for managing account-related entities on your platform. These related entities include account holders, accounts, bank accounts, shareholders, and verification-related documents. The management operations include actions such as creation, retrieval, updating, and deletion of them.\n\nFor more information, refer to our [documentation](https://docs.adyen.com/marketplaces-and-platforms/classic).\n## Authentication\nYour Adyen contact will provide your API credential and an API key. To connect to the API, add an `X-API-Key` header with the API key as the value, for example:\n\n ```\ncurl\n-H \"Content-Type: application/json\" \\\n-H \"X-API-Key: YOUR_API_KEY\" \\\n...\n```\n\nAlternatively, you can use the username and password to connect to the API using basic authentication. For example:\n\n```\ncurl\n-U \"ws@MarketPlace.YOUR_PLATFORM_ACCOUNT\":\"YOUR_WS_PASSWORD\" \\\n-H \"Content-Type: application/json\" \\\n...\n```\nWhen going live, you need to generate new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).\n\n## Versioning\nThe Account API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.\n\nFor example:\n```\nhttps://cal-test.adyen.com/cal/services/Account/v6/createAccountHolder\n```"
  x-timestamp: '2023-05-30T15:27:20Z'
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
servers:
- url: https://cal-test.adyen.com/cal/services/Account/v6
tags:
- name: Cardorders
paths:
  /cardorders:
    get:
      tags:
      - Cardorders
      summary: Adyen Get a List of Card Orders
      description: Returns a paginated list of card orders.
      x-addedInVersion: '1'
      operationId: get-cardorders
      x-sortIndex: 1
      x-methodName: listCardOrders
      security:
      - clientKey: []
      - BasicAuth: []
      - ApiKeyAuth: []
      parameters:
      - description: 'The unique identifier of the card order. '
        name: id
        in: query
        required: false
        schema:
          type: string
      - description: The unique identifier of the card manufacturer profile.
        name: cardManufacturingProfileId
        in: query
        required: false
        schema:
          type: string
      - description: The status of the card order.
        name: status
        in: query
        required: false
        schema:
          type: string
      - description: 'The unique code of the card manufacturer profile.


          Possible values: **mcmaestro**, **mc**, **visa**, **mcdebit**. '
        name: txVariantCode
        in: query
        required: false
        schema:
          type: string
      - description: Only include card orders that have been created on or after this point in time. The value must be in ISO 8601 format. For example, **2021-05-30T15:07:40Z**.
        name: createdSince
        in: query
        required: false
        schema:
          format: date-time
          type: string
      - description: Only include card orders that have been created on or before this point in time. The value must be in ISO 8601 format. For example, **2021-05-30T15:07:40Z**.
        name: createdUntil
        in: query
        required: false
        schema:
          format: date-time
          type: string
      - description: Only include card orders that have been locked on or after this point in time. The value must be in ISO 8601 format. For example, **2021-05-30T15:07:40Z**.
        name: lockedSince
        in: query
        required: false
        schema:
          format: date-time
          type: string
      - description: Only include card orders that have been locked on or before this point in time. The value must be in ISO 8601 format. For example, **2021-05-30T15:07:40Z**.
        name: lockedUntil
        in: query
        required: false
        schema:
          format: date-time
          type: string
      - description: 'The service center at which the card is issued. The value is case-sensitive. '
        name: serviceCenter
        in: query
        required: false
        schema:
          type: string
      - description: 'Specifies the position of an element in a list of card orders. The response includes a list of card orders that starts at the specified offset.


          **Default:** 0, which means that the response contains all the elements in the list of card orders.'
        name: offset
        in: query
        required: false
        schema:
          format: int32
          type: integer
      - description: The number of card orders returned per page. **Default:** 10.
        name: limit
        in: query
        required: false
        schema:
          format: int32
          type: integer
      responses:
        '200':
          content:
            application/json:
              examples:
                success:
                  $ref: '#/components/examples/get-cardorders-success-200'
              schema:
                $ref: '#/components/schemas/PaginatedGetCardOrderResponse'
          description: OK - the request has succeeded.
        '401':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-401'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Unauthorized - authentication required.
        '403':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-403'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Forbidden - insufficient permissions to process the request.
        '422':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-422'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Unprocessable Entity - a request validation error.
        '500':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-500'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Internal Server Error - the server could not process the request.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /cardorders/{id}/items:
    get:
      tags:
      - Cardorders
      summary: Adyen Get Card Order Items
      description: Returns the item list of a specific card order.
      x-addedInVersion: '1'
      operationId: get-cardorders-id-items
      x-sortIndex: 2
      x-methodName: getCardOrderItems
      security:
      - clientKey: []
      - BasicAuth: []
      - ApiKeyAuth: []
      parameters:
      - description: The unique identifier of the card order.
        name: id
        in: path
        required: true
        schema:
          type: string
      - description: 'Specifies the position of an element in a list of card orders. The response includes a list of card order items that starts at the specified offset.


          **Default:** 0, which means that the response contains all the elements in the list of card order items.'
        name: offset
        in: query
        required: false
        schema:
          format: int32
          type: integer
      - description: The number of card order items returned per page. **Default:** 10.
        name: limit
        in: query
        required: false
        schema:
          format: int32
          type: integer
      responses:
        '200':
          content:
            application/json:
              examples:
                success:
                  $ref: '#/components/examples/get-cardorders-id-items-success-200'
              schema:
                $ref: '#/components/schemas/PaginatedGetCardOrderItemResponse'
          description: OK - the request has succeeded.
        '401':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-401'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Unauthorized - authentication required.
        '403':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-403'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Forbidden - insufficient permissions to process the request.
        '422':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-422'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Unprocessable Entity - a request validation error.
        '500':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-500'
              schema:
                $ref: '#/components/schemas/RestServiceError'
          description: Internal Server Error - the server could not process the request.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    CardOrder:
      properties:
        beginDate:
          description: The date when the card order is created.
          format: date-time
          type: string
        cardManufacturingProfileId:
          description: The unique identifier of the card manufacturer profile.
          type: string
        closedDate:
          description: The date when the card order processing ends.
          format: date-time
          type: string
        endDate:
          description: 'The date when you manually closed the card order.


            Card orders are automatically closed by the end of the day it was created. If you manually closed it beforehand, the closing date is shown as the `endDate`.'
          format: date-time
          type: string
        id:
          description: The unique identifier of the card order.
          type: string
        lockDate:
          description: The date when the card order processing begins.
          format: date-time
          type: string
        serviceCenter:
          description: The service center.
          type: string
        status:
          description: 'The status of the card order.


            Possible values: **Open**, **Closed**.'
          enum:
          - closed
          - open
          type: string
      type: object
    PaginatedGetCardOrderResponse:
      properties:
        cardOrders:
          description: Contains objects with information about card orders.
          items:
            $ref: '#/components/schemas/CardOrder'
          type: array
        hasNext:
          description: Indicates whether there are more items on the next page.
          type: boolean
        hasPrevious:
          description: Indicates whether there are more items on the previous page.
          type: boolean
      required:
      - hasPrevious
      - hasNext
      type: object
    RestServiceError:
      properties:
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        errorCode:
          description: A code that identifies the problem type.
          type: string
        instance:
          description: A unique URI that identifies the specific occurrence of the problem.
          type: string
        invalidFields:
          description: Detailed explanation of each validation error, when applicable.
          items:
            $ref: '#/components/schemas/InvalidField'
          type: array
        requestId:
          description: A unique reference for the request, essentially the same as `pspReference`.
          type: string
        response:
          description: JSON response payload.
          $ref: '#/components/schemas/JSONObject'
        status:
          description: The HTTP status code.
          format: int32
          type: integer
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        type:
          description: A URI that identifies the problem type, pointing to human-readable documentation on this problem type.
          type: string
      required:
      - type
      - errorCode
      - title
      - detail
      - status
      type: object
    CardOrderItem:
      properties:
        balancePlatform:
          description: The unique identifier of the balance platform.
          type: string
        card:
          description: 'The status of the card delivery.


            Possible values: **created**, **rejected**, **processing**, **produced**, **shipped**, **delivered**, **notApplicable**, **unknown**. '
          $ref: '#/components/schemas/CardOrderItemDeliveryStatus'
        cardOrderItemId:
          description: The unique identifier of the card order item.
          type: string
        creationDate:
          description: The date and time when the event was triggered, in ISO 8601 extended format. For example, **2020-12-18T10:15:30+01:00**.
          format: date-time
          type: string
        id:
          description: The ID of the resource.
          readOnly: true
          type: string
        paymentInstrumentId:
          description: The unique identifier of the payment instrument related to the card order item.
          type: string
        pin:
          description: Contains information about the status of the PIN delivery.
          $ref: '#/components/schemas/CardOrderItemDeliveryStatus'
        shippingMethod:
          description: The shipping method used to deliver the card or the PIN.
          type: string
      type: object
    InvalidField:
      properties:
        message:
          description: Description of the validation error.
          type: string
        name:
          description: The field that has an invalid value.
          type: string
        value:
          description: The invalid value.
          type: string
      required:
      - name
      - value
      - message
      type: object
    PaginatedGetCardOrderItemResponse:
      properties:
        data:
          description: List of card order items in the card order batch.
          items:
            $ref: '#/components/schemas/CardOrderItem'
          type: array
        hasNext:
          description: Indicates whether there are more items on the next page.
          type: boolean
        hasPrevious:
          description: Indicates whether there are more items on the previous page.
          type: boolean
      required:
      - data
      - hasPrevious
      - hasNext
      type: object
    JSONObject:
      type: object
    CardOrderItemDeliveryStatus:
      properties:
        errorMessage:
          description: An error message.
          type: string
        status:
          description: The status of the PIN delivery.
          enum:
          - created
          - delivered
          - notApplicable
          - processing
          - produced
          - rejected
          - shipped
          - unknown
          type: string
        trackingNumber:
          description: The tracking number of the PIN delivery.
          type: string
      type: object
  examples:
    generic-500:
      summary: Response code - 500 Internal Server Error
      value:
        type: https://docs.adyen.com/errors/general/internal
        title: An internal error happened
        status: 500
        detail: Unrecoverable error while trying to create payment instrument
        requestId: 1WAF555PLWNTLYOQ
        errorCode: '00_500'
    get-cardorders-id-items-success-200:
      summary: Item list of a specific card order retrieved
      description: Example response for retrieving the item list of a specific card order
      value:
        data:
        - card:
            status: shipped
          cardOrderItemId: UNIQUE_CARD_ORDER_ITEM_ID
          paymentInstrumentId: UNIQUE_PAYMENT_INSTRUMENT_ID
          pin:
            status: produced
          shippingMethod: Cardholder Post Basic National
        hasNext: false
        hasPrevious: false
    generic-401:
      summary: Response code - 401 Unauthorized
      value:
        type: https://docs.adyen.com/errors/security/unauthorized
        title: Unauthorized
        status: 401
        detail: Not authorized to access this service.
        errorCode: '00_401'
    get-cardorders-success-200:
      summary: List of card orders retrieved
      description: Example response for retrieving a paginated list of card orders
      value:
        cardOrders:
        - beginDate: '2022-12-05T00:00:00+01:00'
          cardManufacturingProfileId: UNIQUE_CARD_MANUFACTURER_PROFILE_ID
          endDate: '2022-12-06T00:00:00+01:00'
          id: UNIQUE_CARD_ORDER_ID
          lockDate: '2023-04-14T16:43:02+02:00'
          serviceCenter: IDEMIA Sittard
          status: closed
        hasNext: true
        hasPrevious: false
    generic-403:
      summary: Response code - 403 Forbidden.
      value:
        type: https://docs.adyen.com/errors/security/unauthorized
        title: Forbidden
        status: 403
        detail: Not the right permission to access this service.
        errorCode: '00_403'
    generic-422:
      summary: Response code - 422 Unprocessable Entity.
      value:
        type: https://docs.adyen.com/errors/general/invalid-field-value
        title: Invalid Payment Instrument information provided
        status: 422
        detail: The balanceAccountId can only be changed when the status is Inactive or Requested
        requestId: 1W1UI15PLVGC9V8O
        errorCode: '30_031'
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
x-groups:
- Account holders
- Accounts
- Verification
