openapi: 3.2.0
info:
  version: '71'
  x-publicVersion: true
  title: Adyen Checkout Session API
  description: This is the description of your API.
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
servers:
- url: https://checkout-test.adyen.com/v71
tags:
- name: Session
paths:
  /sessions/{sessionId}:
    get:
      tags:
      - Session
      summary: Adyen Get the Result of a Payment Session
      description: Returns the status of the payment session with the `sessionId` and `sessionResult` specified in the path.
      x-addedInVersion: '68'
      operationId: get-sessions-sessionId
      x-sortIndex: 2
      x-methodName: getResultOfPaymentSession
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      parameters:
      - description: A unique identifier of the session.
        name: sessionId
        in: path
        required: true
        schema:
          type: string
      - description: The `sessionResult` value from the Drop-in or Component.
        name: sessionResult
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                success:
                  $ref: '#/components/examples/get-sessions-sessionId-success-200'
              schema:
                $ref: '#/components/schemas/SessionResultResponse'
          description: OK - the request has succeeded.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  examples:
    get-sessions-sessionId-success-200:
      summary: 'Response code: 200 - Success'
      description: The status of the session with the specified ID.
      value:
        id: CS12345678
        status: completed
  schemas:
    SessionResultResponse:
      properties:
        id:
          description: A unique identifier of the session.
          type: string
        status:
          description: "The status of the session. The status included in the response doesn't get updated. Don't make the request again to check for payment status updates.\n\nPossible values:\n\n         * **completed**  The shopper completed the payment. This means that the payment was authorized.\n         * **paymentPending**  The shopper is in the process of making the payment. This applies to payment methods with an asynchronous flow.\n         * **refused**  The session has been refused, due to too many refused payment attempts. Shoppers can no longer complete the payment with this session.\n         * **canceled**  The shopper canceled the payment.\n         * **active**  The session is still active and can be paid.\n         * **expired**  The session expired (default: 1 hour after session creation). Shoppers can no longer complete the payment with this session.\n"
          enum:
          - active
          - canceled
          - completed
          - expired
          - paymentPending
          - refused
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
